server_names_hash_bucket_size 128;

server {
    listen 80 default_server;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
